class Photo < ApplicationRecord

  validates :object_key, presence: true
  validates :uuid, presence: true, uniqueness: true
  enum size: { thumbnail: 400, preview: 1200 }
  before_save :set_size_from_name
  belongs_to :original, class_name: self.name, primary_key: :uuid, foreign_key: :parent_uuid
  belongs_to :event
  has_many :copies, class_name: self.name, primary_key: :uuid, foreign_key: :parent_uuid
  scope :original, -> { where(size: nil) }

  private

    def set_size_from_name
      # name is generated by qq.s3.FineUploaderBasic scaling sizes and matches
      # the keys defined for Photo model size enum
      return unless self.size.nil?
      size_match = name.match /\s\((.+)\)\..+$/
      self.size = size_match[1] if size_match
    end

end
